### ISSUE TITLE
初の記事：ブログの自動化

### ISSUE THREAD

**Issue by zhenbin-z** [splinkns/engineers-blog#13]
https://www.notion.so/55224c1e3a904ffab86b489c8423a032

**Comment by zhenbin-z** [comment]
@choplin 簡単に作ってみました。レビューをお願いします。

**Comment by choplin** [comment]
@zhenbin-z レビューコメントってgithubに書くんでしたっけ？notionの方に書く？

**Comment by choplin** [comment]
全体としてはokだと思います！Great job! いくつかtrivialな点ですが
* miroに私の名前が入っていて外の人は分からないと思うので、「エンジニアメンバーによる内容レビュー」とかにしておくのはどうでしょうか？
* miroとnotionに言及しているところで各サービスを直接埋め込んでますが、スクリーンショットにしておいた方が記事の独立性が上がるのでよいかなと思います。
* このリポジトリの名前ですが、recruitだと広すぎるかなと思うので、engineers-blogとかにするのはどうですか？

**Comment by zhenbin-z** [comment]
@choplin 上記のご指摘を対応しました。
